clear
clc
close all

% load envrionmental conditions and parameters
INPUTS_0_Constants

% vector of transpiration values to evaluate
E_vect = 0:1e-5:1e-2; %in [mol/m^2/s]

% calculations
[E_vect, A_n_vect, R_d_vect, ...
g_w_vect, g_c_vect, g_tot_vect, ...
lambda_vect,  ...
P_x_l_vect, P_x_r_vect, P_0_vect, ...
T_l_vect, VPD_vect, RH_l_vect] = ...
FUNCTION_Hydr_Temp_CAssimilation( ...
E_vect, ... 
R_abs, T_a, h_soil, RH_a, g_b, P_atm, c_a, o_a, ...
LA, r_0, r_b, ERL, k_r_25, ...
rel_k_soil_func, rel_k_r_func, rel_k_x_func, ...
tau_soil, h_soil_star, K_soil_max_25, ...
tau_x, P_x_star, k_x_max_25, ...
alpha, PPFD, Phi_PSII_func, ...
theta_J, theta_c, ...
V_cmax_func, J_max_func, Gamma_star_func, ...
K_c_func, K_o_func, R_d_func, ...
rho, m, g, C_p, emiss, sigma, V_w, R, ...
NSL_c_func, NSL_j_func, r_func);

P_x_l_vect

% plot
figure
tiledlayout(2,1)

% first tile of plot
nexttile(1)
plot(E_vect, A_n_vect, 'b-', 'LineWidth', 2)
xlabel('Transpiration, {\itE} [mol\cdotm^{-2}\cdots^{-1}')
ylabel('Net Assimilation, {\itA_n} [mol\cdotm^{-2}\cdots^{-1}')

% second tile of plot
nexttile(2)
plot(E_vect, lambda_vect, 'b-', 'LineWidth', 2)
xlabel('Transpiration, {\itE} [mol\cdotm^{-2}\cdots^{-1}')
ylabel('Marginal C profit of water, {\itdA_n}/{\itdE}')
ylim([0, max(ylim)])
