function [E_vect, A_n_vect, R_d_vect, ...
g_w_vect, g_c_vect, g_tot_vect, ...
lambda_vect,  ...
P_x_l_vect, P_x_r_vect, P_0_vect, ...
T_l_vect, VPD_vect, RH_l_vect] = ...
FUNCTION_Hydr_Temp_CAssimilation( ...
E_vect, ... 
R_abs, T_a, h_soil, RH_a, g_b, P_atm, c_a, o_a, ...
LA, r_0, r_b, ERL, k_r_25, ...
rel_k_soil_func, rel_k_r_func, rel_k_x_func, ...
tau_soil, h_soil_star, K_soil_max_25, ...
tau_x, P_x_star, k_x_max_25, ...
alpha, PPFD, Phi_PSII_func, ...
theta_J, theta_c, ...
V_cmax_func, J_max_func, Gamma_star_func, ...
K_c_func, K_o_func, R_d_func, ...
rho, m, g, C_p, emiss, sigma, V_w, R, ...
NSL_c_func, NSL_j_func, r_func)

[ P_x_l_vect, P_x_r_vect, P_0_vect, dP_x_ldE_vect] = ...
FUNCTION_Hydraulics(E_vect, m, rho, g, h_soil, T_a, ...
                    LA, r_0, r_b, ERL, k_r_25, ...
                    rel_k_soil_func, rel_k_r_func, rel_k_x_func, ...
                    tau_soil, h_soil_star, K_soil_max_25, ...
                    tau_x, P_x_star, k_x_max_25);

[ T_l_vect, g_w_vect, g_c_vect, g_tot_vect, VPD_vect, dEdg_w_vect, dg_wdg_c_vect, L, RH_l_vect ] = ...
FUNCTION_Conductances_and_Temperature( E_vect, P_x_l_vect, dP_x_ldE_vect, P_atm, ...
                                       R_abs, T_a, RH_a, g_b, r_func, ...
                                       m, C_p, emiss, sigma, V_w, R);

[ A_n_vect, R_d_vect, lambda_vect ] = ...
FUNCTION_Carbon_Assimilation(g_c_vect, T_l_vect, ...
                             alpha, PPFD, Phi_PSII_func, ...
                             theta_J, theta_c, ...
                             V_cmax_func, J_max_func, Gamma_star_func, ...
                             K_c_func, K_o_func, R_d_func, c_a, o_a, ...
                             C_p, emiss, sigma, L, g_b, ...
                             dEdg_w_vect, dg_wdg_c_vect, ...
                             NSL_c_func, NSL_j_func, ...
                             P_x_l_vect, dP_x_ldE_vect); 

end

